baseURL = "https://www.example.com/"
languageCode = "zh-cn"
title = "Hugo Hero 主题"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Hero 是一个多用途 Hugo 主题，具有全屏英雄图像和页面部分。它包含商业或作品集网站的内容类型。"
    meta_og_title = "Hugo Hero 主题"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Hero 是一个多用途 Hugo 主题，具有全屏英雄图像和页面部分。它包含商业或作品集网站的内容类型。"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "服务"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "作品"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "历史"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "联系"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
